### ISSUE TITLE
Better result with pretrained model

### ISSUE THREAD

**Issue by mdyao** [divelab/Noise2Same#3]
Hi, I use the pre-trained model on [Google Cloud]("https://drive.google.com/drive/folders/17ND4m1Ub8AaTOAbKlDJBf42ZzthM8aI0") and the official .ipynb to reproduce the results on Imagenet dataset. However, I get the psnr=22.50, which is higher than  22.26 in the pulished paper. 

Is there any difference between the paper's model and Google cloud's model?
Thanks.

**Comment by ycremar** [comment]
Hi mdyao,

The pre-trained model uses the same model and training configuration as described in the paper. It should match the score in the examples in the released code. The difference is mainly due to randomness during training and is within the acceptable range.
